name: AdvancedFeed
version: 1.0
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10]
description: Advanced Feeding System for PocketMine-MP
author: iiFlamiinBlaze
commands:
 feed:
  description: Commands that feeds the player
  permission: feed.command
  usage: "/feed"
permission:
 feed.command:
  default: op