name: AdvancedFly
main: iiFlamiinBlaze\AdvancedFly
description: An advanced survival fly plugin!
version: 1.4
api: [3.0.0-ALPHA8, 3.0.0-ALPHA9]
author: iiFlamiinBlaze
load: POSTWORLD
commands:
  fly:
    description: "Fly Command"
permissions:
  fly.command:
    description: "AdvancedFly command permission"
    default: op