name: Selector
main: iiFlamiinBlaze\Selector
author: iiFlamiinBlaze
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
version: 1.1.5-ALPHA
description: A lobby selector plugin!
website: http://EruptusPE.tk
load: POSTWORLD
permissions:
  selector.use:
   default: true
   description: Allows you to use Selector!